### PR TITLE
add chrome-dgram as a dependency for bundling with browserify

### PR DESCRIPTION
**Pull request by justchen1369**
[ ] Documentation update
[x] Bug fix
[ ] New feature
[ ] Other, please explain:

I'm not sure what version to bump the package to.
I also took the liberty of creating .gitignore.

### CODE REVIEW

**Review by feross — APPROVED** [review]
LGTM

**Comment by feross** [comment]
> I'm not sure what version to bump the package to.

The maintainer of the package will bump the version when they publish it to npm :) No need to bump it in a PR.

**Comment by feross** [comment]
Published as 1.1.0.

**Comment by justchen1369** [comment]
should I bump the version on the webtorrent repo now?

**Comment by feross** [comment]
No need. The `^` operator in `package.json` will pull in the latest minor and patch versions automatically. You just need to re-run `npm install`.

**Pull request merged**
